[package]
name = "jjb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.56", features = ["derive"] }
fs-err = "3.2.2"

[dev-dependencies]
tempfile = "3.24.0"
